server {
    listen 8080;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/ {
        proxy_pass http://app-api:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /otel/ {
        proxy_pass http://otel-collector:4318/;
    }
}
